<div class="Responsive">
    <div class="Banner" >
        <div class="js-carousel Carousel">
            <div class="js-carouselCtx Carousel-content" >
                <div class="js-carouselList Carousel-content-list">
                    <div class="Carousel-content-item" id="carousel1" data-index="1">
                        <img src="./top/img/DUCbanner.webp" alt="">
                    </div>
                    <div class="Carousel-content-item" id="carousel2" data-index="2">
                        <img src="./top/img/Mean.webp" alt="">
                    </div>
                    <div class="Carousel-content-item" id="carousel3" data-index="3">
                        <img src="./top/img/Contact.webp" alt="">
                    </div>
                </div>
                <div class="js-carouselBtn Carousel-content__btn"></div>
                <div class="js-carouselBtn Carousel-content__btn Carousel-content__btn--right"></div>
            </div>
            <div class="Carousel-nav">
                <div class="js-carouselNavItem Carousel-nav-item Carousel-nav-item--active" data-index="1">
                    <p class="only-pc Carousel-nav-item__txt">Brand</p>
                </div>
                <div class="js-carouselNavItem Carousel-nav-item" data-index="2">
                    <p class="only-pc Carousel-nav-item__txt">Message conveyed</p>
                </div>
                <div class="js-carouselNavItem Carousel-nav-item" data-index="3">
                    <p class="only-pc Carousel-nav-item__txt">Contact Founder</p>
                </div>
            </div>
        </div>
        <div class="Banner-area">
            <a href="#" class="Banner-area__item">
                <img src="./top/img/banner_1.webp" alt="">
            </a>
            <a href="#" class="Banner-area__item">
                <img src="./top/img/banner_2.webp" alt="">
            </a>
        </div>
    </div>
</div>
