<div class="Responsive">
<footer>
        <div class="footer-top">
            <div class="footer-list-top">
                <div class="footer-list-top-item">
                    <h4 class="footer-list-top-item__txt">Mission</h4>
                    <div class="tx-div"></div>
                </div>
                <div class="footer-list-top-item">
                    <p class="footer-list-top-item__txt">This is my own website. The meaning of the DUC brand is me and I also think of Dream Until Cry, like trying my best until sweat and tears have to fall!</p>
                </div>
            </div>
            <div class="footer-list-top">
                <div class="footer-list-top-item">
                    <h4 class="footer-list-top-item__txt">Quick links</h4>
                    <div class="tx-div"></div>
                </div>
                <div class="footer-list-top-item">
                    <a href="#" class="footer-list-top-item__txt">Question and Answer</a>
                </div>
                <div class="footer-list-top-item">
                    <a href="#" class="footer-list-top-item__txt">Warranty and return</a>
                </div>
                <div class="footer-list-top-item">
                    <a href="#" class="footer-list-top-item__txt">Feedback</a>
                </div>
            </div>
            <div class="footer-list-top">
                <div class="footer-list-top-item">
                    <h4 class="footer-list-top-item__txt">Office Hours</h4>
                    <div class="tx-div"></div>
                </div>
                <div class="footer-list-top-item">
                    <p class="footer-list-top-item__txt">Monday - Friday : 7.00 AM - 10.00 PM</p>
                </div>
                <div class="footer-list-top-item">
                    <p class="footer-list-top-item__txt">Saturday : 8.00 AM - 10.00 PM</p>
                </div>
                <div class="footer-list-top-item">
                    <p class="footer-list-top-item__txt">Sunday : Close store</p>
                </div>
            </div>
            <div class="footer-list-top">
                <div class="footer-list-top-item">
                    <h4 class="footer-list-top-item__txt">Others</h4>
                    <div class="tx-div"></div>
                </div>
                <div class="footer-list-top-item">
                    <a href="#" class="footer-list-top-item__txt">Someting for Fun</a>
                </div>
                <div class="footer-list-top-item">
                    <a href="#" class="footer-list-top-item__txt">Click it if you wanna</a>
                </div>
                <div class="footer-list-top-item">
                    <a href="#" class="footer-list-top-item__txt">Thank's for your support</a>
                </div>
            </div>
        </div>
        <div class="footer-social-section">
            <div class="footer-social-overlap footer-social-connect">
                <div class="tx-div-full"></div>
                <p>CONNECT</p>
                <span class="footer-social-small">with</span>
                <p>ME</p>
                <div class="tx-div-full"></div>
            </div>
            <div class="footer-social-overlap footer-social-icons-wrapper">
                <div class="tx-div-full"></div>
                <a href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook-f" aria-hidden="true"></i></a>
                <a href="https://mail.google.com/mail/u/0/#inbox" target="_blank"><i class="fa fa-envelope" aria-hidden="true"></i></a>
                <a href="https://www.instagram.com/" target="_blank"><i class="fab fa-instagram" aria-hidden="true"></i></a>
                <a href="https://www.youtube.com/" target="_blank"><i class="fab fa-youtube" aria-hidden="true"></i></a>
                <a href="tel:0869803404"><i class="fa fa-phone-square" aria-hidden="true"></i></a>
                <div class="tx-div-full"></div>
            </div>
        </div>
        <div class="tx-div-full"></div>
        <div class="footer-social-section">
            <div class="footer-bottom-wrapper">
                <p> © 2020 Copyright : Hồng Đức </p>
            </div>
        </div>
</footer>
</div>
