<header class="only-pc">
    <div class="Responsive">
        <div class="Menu">
            <div class="Menu-brand">
                <div class="Menu-brand__logo">
                    <img src="/ducshop/common/imgs/logo.webp" alt="">
                </div>
                <div class="Menu-brand-search">
                    <div class="Menu-brand-search-location">
                        <p class="js-locationBtn Menu-brand-search-location__txt">Hồ Chí Minh</p>
                        <div class="Menu-brand-search-location-select">
                            <p class="js-locationOpt"><i class="fa fa-map-marker"></i><span> Hồ Chí Minh </span></p>
                            <p class="js-locationOpt"><i class="fa fa-map-marker"></i><span> Hà Nội </span></p>
                        </div>
                    </div>
                    <div class="Menu-brand-search-input">
                        <input type="text" placeholder="Tìm kiếm">
                    </div>
                    <div class="Menu-brand-search-button">
                        <i class="fa fa-search"></i>
                    </div>
                </div>
            </div>
            <div class="Menu-list">
                <div class="Menu-list-item">
                    <div class="Menu-list-item-content">
                        <div class="Menu-list-item-content__icon"><i class="fas fa-tshirt"></i></div>
                        <p class="Menu-list-item-content__txt">TOPS</p>
                    </div>
                    <div class="Menu-list-item-sub">
                        <div class="Menu-list-item-sub-list">
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> T-shirts </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Shirts </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Tanks </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Menu-list-item">
                    <div class="Menu-list-item-content">
                        <div class="Menu-list-item-content__icon"><i class="fas fa-bold"></i></i></div>
                        <p class="Menu-list-item-content__txt">BOTTOMS</p>
                    </div>
                    <div class="Menu-list-item-sub">
                        <div class="Menu-list-item-sub-list">
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Shorts </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Pants </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Joggers </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Menu-list-item">
                    <div class="Menu-list-item-content">
                        <div class="Menu-list-item-content__icon"><i class="fab fa-dyalog"></i></div>
                        <p class="Menu-list-item-content__txt">DENIMS</p>
                    </div>
                    <div class="Menu-list-item-sub">
                        <div class="Menu-list-item-sub-list">
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Denim Jackets </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Denim Pants</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Menu-list-item">
                    <div class="Menu-list-item-content">
                        <div class="Menu-list-item-content__icon"><i class="fab fa-opera"></i></div>
                        <p class="Menu-list-item-content__txt">OUTERWEARS</p>
                    </div>
                    <div class="Menu-list-item-sub">
                        <div class="Menu-list-item-sub-list">
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Jackets </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Bombers </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Hoodies </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Blazers </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Trench Coats</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Menu-list-item">
                    <div class="Menu-list-item-content">
                        <div class="Menu-list-item-content__icon"><i class="fas fa-ring"></i></div>
                        <p class="Menu-list-item-content__txt">ACCESSORIES</p>
                    </div>
                    <div class="Menu-list-item-sub">
                        <div class="Menu-list-item-sub-list">
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Belts </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Handbags </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Hats </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Jewelrys </a>
                            </div>
                            <div class="Menu-list-item-sub-item">
                                <a href="#" class="Menu-list-item-sub-item__txt"> Others</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Menu-list-item">
                    <div class="Menu-list-item-content">
                        <div class="Menu-list-item-content__icon"><i class="fas fa-share-alt"></i></div>
                        <a href="#" class="Menu-list-item-content__txt">SOCIAL</a>
                    </div>
                </div>
                <div class="Menu-list-item">
                    <div class="Menu-list-item-content">
                        <div class="Menu-list-item-content__icon"><i class="far fa-address-card"></i></div>
                        <a href="#" class="Menu-list-item-content__txt">CONTACT</a>
                    </div>
                </div>
                <div class="Menu-list-item">
                    <div class="Menu-list-item-content">
                        <div class="Menu-list-item-content__icon"><i class="fas fa-feather-alt"></i></div>
                        <a href="#" class="Menu-list-item-content__txt">TERMS</a>
                    </div>
                </div>
                <div class="Menu-list-item">
                    <div class="Menu-list-item-content">
                        <div class="Menu-list-item-content__icon"><i class="fa fa-gift"></i></div>
                        <a href="#" class="Menu-list-item-content__txt">PROMOTION</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<header class="only-sp">
    <div class="js-nav Nav">
        <div class="Nav-content">
            <div class="Nav__logo">
                <img src="./common/imgs/logo.webp" alt="Dream Until Cry">
            </div>
            <div class="Nav-search">
                <div class="Nav-search-content">
                    <div class="Nav-search__input">
                        <input type="text" placeholder="Tìm kiếm">
                    </div>
                    <div class="Nav-search__btn"><i class="fa fa-search"></i></div>
                </div>
            </div>
            <div class="Nav-hamburger">
                <div class="js-navHamburger Nav-hamburger-content">
                    <span class="Nav-hamburger-content__ico"></span>
                    <span class="Nav-hamburger-content__ico"></span>
                    <span class="Nav-hamburger-content__ico"></span>
                </div>
            </div>
        </div>
        <div class="Nav-menu">
            <div class="Nav-menu-content">
                <div class="Nav-menu-content-list">
                    <p class="Nav-menu-content-item">TOPS</p>
                    <p class="Nav-menu-content-item">BOTTOMS</p>
                    <p class="Nav-menu-content-item">DENIMS</p>
                    <p class="Nav-menu-content-item">OUTERWEARS</p>
                    <p class="Nav-menu-content-item">ACCESSORIES</p>
                    <p class="Nav-menu-content-item">SOCIAL</p>
                    <p class="Nav-menu-content-item">CONTACT</p>
                    <p class="Nav-menu-content-item">TERMS</p>
                    <p class="Nav-menu-content-item">PROMOTION</p>
                </div>
                <div class="Nav-menu-content-footer">
                    <div class="Nav-menu-content-footer-contact">
                        <a href="tel:0869803404">0869803404</a>
                    </div>
                    <p style="font-style:italic;text-align: center;">Đây là web của Hồng Đức! Nếu có liên hệ hãy gọi số bên trên</p>
                </div>
            </div>
        </div>
    </div>
</header>
